<Project>
	<PropertyGroup>
		<AssemblyOriginatorKeyFile>$(SolutionDir)StrongName.Development.snk</AssemblyOriginatorKeyFile>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
		<DelaySign>false</DelaySign>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<!-- Below is a workaround for https://github.com/dotnet/roslyn/issues/41640 -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!-- LangVersion: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version -->
		<LangVersion>default</LangVersion>
		<!-- Below is for the same workaround as above. -->
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<!-- Package 'SQLitePCLRaw.lib.e_sqlite3' 2.1.2 has a known high severity vulnerability, https://github.com/advisories/GHSA-2m69-gcr7-jv3q -->
		<NoWarn>$(NoWarn);NU1903</NoWarn>
		<SignAssembly>true</SignAssembly>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
</Project>