// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RegionOrebroLan.Platina.Data.Sqlite;

namespace RegionOrebroLan.Platina.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqlitePlatinaContext))]
    [Migration("20200911100326_Platina")]
    partial class Platina
	{
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("RegionOrebroLan.Platina.Data.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Confirmed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("File")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileExtension")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordIdentities")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2000);

                    b.Property<string>("Organization")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<byte[]>("PdfFile")
                        .HasColumnType("BLOB");

                    b.Property<string>("PdfFileExtension")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Saved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
